name: aibuddycraft
main: com.crissomar.aibuddycraft.Plugin
version: 0.1
api-version: 1.15
depend:
  - Citizens
commands:
  summonbuddy:
    description: Crea un npc
    usage: /summonnpc <nombre>
    permission: aibuddycraft.summonnp
  buddy:
    description: Edita el npc
    usage: /buddy <edit|skin|remove> <nombre> [argumentos]
    permission: aibuddycraft.buddy